spring:
  application:
    name: "gateway"
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI:http://localhost:8888}
      fail-fast: false

ribbon:
  ReadTimeout: 60000

management:
  endpoints:
    web:
      exposure:
        include: ["env", "refresh","health","httptrace","info", "info", "metrics", "prometheus"]