version: '3'

services:
  prometheus:
    image: prom/prometheus
    restart: on-failure
    ports:
      - 9090:9090
    networks:
      - msa-network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    restart: on-failure
    ports:
      - 3000:3000
    networks:
      - msa-network

networks:
  msa-network:
    external: true
